### ISSUE TITLE
Request: For Popcorn Time Slackbuild 

### ISSUE THREAD

**Issue by ghost** [fsLeg/SlackBuilds#1]
Hello,

I see you made a slackbuild for popcorntime, but that is the one from the popcorn-time.se website, and I read that it is not a good fork to use, and the one from popcorntime.io is better;

https://git.popcorntime.io/groups/popcorntime

I'd like to be able to compile this from source.

I was looking at what they are doing with it on Arch to get an idea of what is going on;

https://aur.archlinux.org/packages/popcorntime-git/

Thank you for your consideration in making this.

**Comment by fsLeg** [comment]
My SlackBuild **is** for the version from popcorntime.io. The one from popcorn-time.se doesn't work anyway and seems abandoned, even though the developers claim otherwise.

About the source. I tried that and, even though the resulting program works fine, it's just too nasty: it requires node.js and **a lot** of NPM modules. After installing all the required modules, the directory with Popcorn-Time weighed mode than 500 Mb with no explanation what was actually needed. So I prefered to just repackage the static build provided by the developers.

The PKGBUILD from AUR looks interesting, I'll try this way of building the package later. It'll add at least one dependency, though.

**Comment by ghost** [comment]
Hi,

My bad, not sure why I thought it was the .se one hmm...

Ahhh 500 megs modules, LOL, I can understand that, errrr :(

Well hopefully looking at the Arch script(s) it can be made simple. 

It would just be nice to have a source build that way you can always stay on top of the latest git builds...

By the way I tried your slackbuild with the binary, yes it's certainly easy and seems to run good, I'm just one of those geeks that hates using a binary from someone, I'd rather compile the source.

Thanks for your time and consideration over this.

P.S. It crashes playing on mpv, so another great reason, at least for me to try and get the lastest git compiled. :)

**Comment by ghost** [comment]
HOLY CRAP you're right, this flippin thing downloads so much crap. 

For the life of me I can't figure out how to do it as a slackbuild because it seems like you need to build it as a user. So I just ran the make_popcorn.sh script. It's been running for a while and if it builds it, then I'll just use like your SBo and package this from git.

Then thank goodness I have a clonezilla backup I'll stick back in afterwards to make sure all this crap is cleaned out! LMAO

Sheesh I think it's better to build this in a VM or a spare box! ;)

**Comment by ghost** [comment]
Hi,

So I finally got this working, you have to make sure you use node 0.10x I used 0.10.37

I created a slackbuild for bower and grunt, not sure if they are 100% correct but it does seem to be working, and then with Popcorn-Time I just downloaded the latest master tar and ran the script it comes with, `make_popcorn.sh`. 

I'll have to try and compile it from the cmd line next time with the cmds to see how it goes. But the odd thing is, this thing wants to be built as a user, at least I think you have to do it this way.

Here's some nfo;

https://git.popcorntime.io/popcorntime/desktop/blob/master/CONTRIBUTING.md

Here's my slackbuilds for bower and grunt you can have a play with, hope they help.

---

PRGNAM=bower
VERSION=${VERSION:-1.3.12}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 ( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 ) -exec chmod 755 {} \; -o \
 ( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 ) -exec chmod 644 {} \;

npm install -g bower --prefix "$PKG/usr"

cd $TMP/$PRGNAM-$VERSION
mv CHANGELOG.md CHANGELOG 
mv CONTRIBUTING.md CONTRIBUTING
mv HOOKS.md HOOKS
mv README.md README

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGELOG CONTRIBUTING HOOKS LICENSE README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

---

PRGNAM=grunt
VERSION=${VERSION:-0.4.5}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 ( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 ) -exec chmod 755 {} \; -o \
 ( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 ) -exec chmod 644 {} \;

npm install -g grunt-cli --prefix "$PKG/usr"

cd $TMP/$PRGNAM-$VERSION
mv CONTRIBUTING.md CONTRIBUTING
mv README.md README

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS CHANGELOG CONTRIBUTING LICENSE-MIT README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

**Comment by fsLeg** [comment]
I think that's too much effort. You can already build it yourself, writing SlackBuild for this is too much hassle. Besides, that's _three_ dependencies just to build, there's no need for them (I think) to actually run the program. And the static build works just fine.

**Comment by ghost** [comment]
LOL....

Hey Slackers don't quit so easy, and besides I created a working slackbuild! :)

You don't want to be stuck on a binary, for various reasons, things broke, new changes, etc...

But hey should I have to explain to a Slacker the benefits of compiling from source? LOL...

I'm just playing with you, this was not so hard afterall, I was just letting all this node crap at first intimidate  me.

But it would be nice if this can be compiled against all the dependancies without needing to install them, I'm not sure, or also compile the slackbulld and have all these /paths it installs into /root & /tmp kept like in the /tmp build /path instead... But I'm not good enough a Slacker to figure that out, hehe...

`Just be sure to install  node 0.10.x I did 0.10.37`

Hey this will only take like 15-20mins for everything to compile and install. :)

I cloned from git and I changed the VERSION in the slackbuild to the date, just to keep an eye on when I compiled.

https://git.popcorntime.io/popcorntime/desktop.git

bower install is something I need to see if it can be compiled without it, Arch doesn't use it...

Arch only runs; `npm install & grunt build` hmm

By the way when you run this, it installs these /paths you can remove later;

```
/root/.cache/bower
/root/.config/configstore/
/root/.local/share/bower
/root/.npm
/tmp/npm-files...
/tmp/root
```

Here's the slackbuild I made from yours...

---

PRGNAM=Popcorn-Time
VERSION=${VERSION:-03.22.15}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  BITS="32"
elif [ "$ARCH" = "i686" ]; then
  BITS="32"
elif [ "$ARCH" = "x86_64" ]; then
  BITS="64"
else
  echo "Your architecture is unsupported."
  exit 1
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 ( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 ) -exec chmod 755 {} \; -o \
 ( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 ) -exec chmod 644 {} \;

npm install -g grunt-cli bower
npm install
bower install --allow-root
grunt build

mkdir -p $PKG/opt/Popcorn-Time
cd  $TMP/$PRGNAM-$VERSION/build/releases/$PRGNAM/linux64/$PRGNAM
cp Popcorn-Time $PKG/opt/Popcorn-Time
cp nw.pak $PKG/opt/Popcorn-Time
cp libffmpegsumo.so $PKG/opt/Popcorn-Time

cd $TMP/$PRGNAM-$VERSION
rename ".md" "" *
rename ".txt" "" *

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGELOG CONTRIBUTING LICENSE README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/share/applications
cat $CWD/popcorn-time.desktop > $PKG/usr/share/applications/popcorn-time.desktop
for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256; do
  mkdir -p $PKG/usr/share/icons/hicolor/$geometry/apps
  convert -resize $geometry $CWD/popcorntime.png $PKG/usr/share/icons/hicolor/$geometry/apps/popcorn-time.png
done

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l n -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}

---

HAVE FUN! :)

**Comment by fsLeg** [comment]
It's not necessary to install grunt and bower globally, so you can omit the `-g` flag in `npm install` (don't forget to change path to grunt accordingly). Installation of bower is necessary, though, because it is used by... well, something. I only see some bower-specific files in the Popcorn-Time directory, like `bower.json`, besides it's listed as a dependency.

The cleaning afterwards really is a chore, because node.js installs its module list into the home directory, then there's bower with its own special directories... There should be some unspecified in the documentation flags that control where all these files end up, otherwise all I can think of is some sort of chroot, which might make the SlackBuild a real mess. I may google some ways to limit the spread of files tomorrow evening.

BTW, I built Popcorn-Time with node-0.12 (from SBo) and, a few warnings aside, everything went fine.

**Comment by ghost** [comment]
Yes having the control of where all these files ends up would be nice.

WoOT, GLAD to hear you compiled it, see, it wasn't so bad was it? hehe :)

So what should I change these build options?

```
npm install -g grunt-cli bower
npm install
bower install --allow-root
grunt build
```

without `-g` I can understand to do like this then? `npm install grunt-cli bower` 

By the way I also found these other cmds being used in Arch build;

```
grunt css
grunt bower_clean
grunt nodewebkit
```

I wonder if this `grunt bower_clean` cleans all the mess out?

https://www.npmjs.com/package/grunt-bower-clean

Change path for grunt accordinly I don't understand?

When I used node 0.12.0 popcorn complained it couldn't find module torrent-stream and when I clicked on the button Watch, it did nothing, and would not play, until I used node 0.10.x

Ok I built it against node 0.12.0 using these options and it worked;

```
npm install grunt-cli bower
npm install
bower install --allow-root
grunt build
```

It gave me a warning saying how I should use -g to install grunt and bower, hmm

**Comment by ghost** [comment]
AHHHH I figured out how to remove the `/root/.npm` at least this worked when building grunt, I'm assuming also the same for bower and poprcorn...

`npm config set cache $TMP/npm-cache`

https://docs.npmjs.com/files/folders

But then in /root you get a config file for it; `/root/.nmprc` which shows the /path, so now to clean that out next LOL...

`P.S.` After posting the above information I realized by setting a cache to a different path it then creates a .npmrc in /root so in order to delete that you need to use; `npm config delete cache`

So now no more /root/.npm :)

Ok 90% of the way there, now I'm trying to figure out how to get rid of the /paths bower creates;

```
/root/.cache/bower
/root.config/configstore 
/root/.local/bower
```

There's a cmd which cleans out the /root/.cache, but it still leaves the /paths
`bower cache clean --allow-root`

So this is what I have...

bower slackbuild

```
npm config set cache $TMP/npm-cache
npm install -g bower --prefix=$PKG/usr
npm config delete cache
```

grunt slackbuild

```
npm config set cache $TMP/npm-cache
npm install -g grunt-cli --prefix=$PKG/usr 
npm config delete cache
```

popcorn slackbuild

```
npm config set cache $TMP/npm-cache
npm install grunt-cli bower
npm install
bower install --allow-root
grunt build
bower cache clean --allow-root
npm config delete cache
```

**Comment by fsLeg** [comment]
Using `npm config set/delete` is not a very good thing to have in a SlackBuild. What if the user has already set this value? And you'll first overwrite and then remove it.

There's no `bower install` command in the Popcorn-Time documentation, neither it is in the Arch's PKGBUILD. I also built Popcorn-Time without it, so I think you can skip it, maybe it'll even clean thing up a bit.

> Change path for grunt accordinly I don't understand?

When you don't install grunt globally, it ends up in ./node_modules/grunt-cli/bin, which is not in $PATH, so you'll have to take this into account when calling the `grunt build` command.

I still think that installing three packages, which don't even install very cleanly, just to _build_ another package is a good idea, when we have the officially supported static binaries that work. To make a package for Popcorn-Time by hand is less hassle than trying to script it in a clean way, and we still end up with the same static binary the developers provide us.

Also, please use [gist](https://gist.github.com/) when you're pasting big snippets of code, like contents of a SlackBuild.

**Comment by ghost** [comment]
Hi,

Well true the end-user could run the `npm config set/delete` cmds before the build and after. But if you are talking about this slackbuild as example for yourself to place up on the GitHub, I would figure the solution is to place information in a README explaining this, then I don't really see why it's a problem? 

Ahh bower install, yes good point, to be honest I just did that because I saw it listed in the src; `make_popcorn.sh`;

```
 echo "Setting up Bower"
    if bower install; then
        echo "Bower successfully installed"
    else
        echo "Encountered an error while installing bower"
        exit 4
    fi
```

So bower install is not needed?

I'm still trying to wrap my head around all this npm, grunt, bower crap and nodes, because when you say Globally, what about when grunt is first installed with the slackbuild in the /usr/lib64/node_modules/grunt-cli/ /path?

So I removed the `-g` as, `npm install grunt-cli bower` and everything installed fine, it just gave a warning, I forgot the exact wording about the warning wanting grunt globally, but the install worked fine and at the end said, it was done without errors.

So everytime one of these src you compile and we run the grunt install command it's downloading it and placing it in another path to use for this project, then I don't get the point of why installing the slackbuild?

Not sure I followed your last comments, you meant instead installing 3 packages `not` a good idea?

I'm finding this difficult to understand coming from a Slackware user the benefits of grabbing the latest commits to fixes and compiling it theirself, that you don't see these benefits? Hmm 

Here's a perfect example on another project, the dolphin-emulator for Wii & GameCube;

https://dolphin-emu.org/download/

Most distros are going to pack it with the Dolphin 4.0.2 version, but have a look at all the development and fixes going on above it in the Development branch, the dolphin devs pump out fixes like this daily, and I personally use dolphin on these development branches because it works so much better then the last stable version.

It's the same for Popcorn-Time, we geeks all use the latest development for the latest goodies and fixes, of course providing it is stable enough and Popcorn-Time is. :)

Hey I didn't write the rule book, LOL, but it is a fact that Slackware is a hands on distro and most Slackware users like myself prefer to compile the source, rather then just taking a precompiled binary. Of course now Gentoo is the extreme with compiing, Arch in there too. But Slackers taking precompiled binaries over compiling? Oh that's Slack blasphemy LOL... :)

In all my Slacking years, I think I've only used a precompiled binary 1 or 2 times...

Sorry about not using gist, I forgot about it...

**Comment by ghost** [comment]
Oh, by the way I wasn't trying to be rude, so please don't take anything I'm saying personally, I'm just saying things is all, the way I see them as a Slacker.  And I really appreciate your help too! :)

I really love the simplicty of slack and being able to be hands on, so outside of the Slack repo, with an exception to a few pkgs, I compile everything, kernel included. I love compiling, hacking and tinkering. I've really learnt a lot over the years doing so, and I'm having fun too with Poprcorn-Time doing it also.

Plus I've found a few bugs and made some reports, so when those get commited, it will be nice to grab the latest source from git and run Poprcorn with these fixes.

And let's not forget, when you compile, you can make configuration changes, I can't begin to tell you how many apps I've stripped out options, only to see the app perform better/faster, with less bloat...

thanks 

P.S. Getting back also to this global thing, I just installed the bower slackbuild and I removed `-g` and it was going to install to;

```
/usr/node_modules/
```

With -g it installs bower to; `/usr/lib64/node_modules`

So I don't get this from a Linux perspective of local & global, to me in Linux terms, local would be my $HOME and gloabl is installed into any system /path... Hmm

So these differences between `/usr/node_modules/` & `/usr/lib64/node_modules`, I don't understand?

**Comment by ghost** [comment]
If I don't do the bower install popcorn doesn't run for me, I get this from the cmd line;

[27964:0323/185611:INFO:CONSOLE(1)] "Uncaught ReferenceError: vjs is not defined", source: app://host/src/app/vendor/videojshooks.js (1)

[27964:0323/185611:INFO:CONSOLE(36)] "Uncaught ReferenceError: jQuery is not defined", source: app://host/src/app/lib/jquery.plugins.js (36)

So did you run popcorn after you built it without running bower install?

Hmm

**Comment by fsLeg** [comment]
> I would figure the solution is to place information in a README explaining this, I don't really see why it's a problem?

I try to keep my scripts generic, minimal and clean. Making user clean up after building a package is not very polite.

> I'm finding this difficult to understand coming from a Slackware user the benefits of grabbing the latest commits to fixes and compiling it theirself, that you don't see these benefits?

The benefits of the bleeding edge software? Fixes to some bugs, maybe some new features, also possible crashes and new bugs. Using the latest version from the development branch is recommended and encouraged if you want to test the software and report/fix bugs. It's not recommended if you just want a program to work and do its thing, in which case using the latest (or even a bit older) version is perfectly reasonable and enough for most users. Personally, there are maybe half a dozen programs I would want (in some cases, require) the latest possible version, but that's more like an exception, because all other packages are kept at their stable versions with which I am happy.

Slackware is conservative and very stable. If anything, Slackware user would want a stable version first, if he isn't a developer or a tester. Using bleeding edge software seems more like Arch's prerogative.

> Not sure I followed your last comments, you meant instead installing 3 packages **not** a good idea?

Yes. I mean, if you're going to install node, bower and grunt as separate packages, then it's excessive. If you want, you could install bower and grunt temporarily within Popcorn-Time's script as they are not needed anywhere else.

> outside of the Slack repo, with an exception to a few pkgs, I compile everything, kernel included

I have a good quote for this: "Some people do not want to build every package from source (this is Slackware, not Gentoo) and are happy with using pre-built packages from trusted sources or packagers." -- [AlienBOB](http://www.linuxquestions.org/questions/slackware-14/skype-4-3-a-4175508618/page11.html#post5232774).

The Gentoo way proved over years that the benefit of compiling everything from source by yourself is very small (unfortunately, I don't remember where I read that). Pre-compiled programs will have pretty much the same performance as the ones you compiled yourself, given you use the same options to compile your package.

> I can't begin to tell you how many apps I've stripped out options, only to see the app perform better/faster, with less bloat

I'm impressed. You seem to closely know hella lot of different programs. I usually really care only about a dozen programs' compilation options at best and have no idea or care about other packages or libraries.

> I removed `-g` and it was going to install to `/usr/node_modules/`

Strange. It should have installed into `./node_modules`. Probably it's because you installed it as root. BTW, Arch's policy is to only become superuser when necessary, usually only when installing a package.

> If I don't do the bower install popcorn doesn't run for me

Strange again. All I did was

```
npm install bower grunt-cli
npm install
./node_modules/.bin/grunt build
```

As you can see, no `bower install`. Everything built and ran just fine. Maybe I just have some leftovers somewhere in the system from my fiddling with Popcorn-Time's source back in September...

---

Anyway, I see that this conversation is on the edge of a holy war. So I'll just summarize my position about writing a script to build the git version of Popcorn-Time: I don't see the point.
1. The official binaries work just fine. Even LibreOffice's build script from SBo just repackages official pre-compiled binaries, I can't see why can't I use the same approach.
2. Using node.js modules results in a lot to clean up after building the package as root. In fact, I think there'll be more cleaning up in the script than the actual compiling. Even making the package by hand will take less effort.
3. You seem to have enough knowledge and experience to be able to compile Popcorn-Time from git yourself. You already kinda wrote the script to automatize the building process, so isn't that enough for you? If you want to test the program after the latest commits and report bugs, feel free to do that, the developers will be grateful.
4. People usually only care for the program to do what it's supposed to do and, unlike popcorn-time.se, popcorntime.io actually does work and the latest stable version doesn't fall that far behind the master git branch. I am fine with the stable version and I am pretty sure that most of their users are fine with it too.

**Comment by ghost** [comment]
Hi fsLeg, oh no Holy War, LOL, I'm just chatting is all, so please don't ever let anything I say bother you, I would never try to offend or upset the person that is trying to help me! :)

HEY I hope I didn't say something to upset you that you closed this?

Yes Slack is certainly all about stability, sorry for the confusion, I would never run Slackware like on current and bleeding edge for the System, I just meant development on some apps is all, like Popcorn-Time. Not sure Popcorn-Time as example running it as a development version would cause the system stability issues. Actually to be honest, I don't recall any developmental versions of an app ever causing me problems running Slack, all I ever saw in the past was maybe something not working properly is all in the app.

With the `./node_modules` not sure I follow, it has to be installed as root to go into the / root of the system. 

So not sure how you'd have `./node_modules` installed... If you meant as a user in your $HOME? But for this I'm thinking about the `node` pkg below if this is what you mean?

http://slackbuilds.org/repository/14.1/network/node/

Yes I think I have this going ok, but I was hoping since I saw you had the slackbuild for Popcorn-Time you might have fun and be interested in exploring doing this from the source. From one Slacker to another Slacker. :)

To be honest I'm not seeing much of any mess, bower and grunt Slackbuilds on their own seem to build and install just fine, not sure I followed you in the past about the mess.

Right now all the npm-files are going to /tmp and these 3 /paths are all I have to figure out how to clean, I mean if there's a command to automate it;

```
/root/.cache/bower
/root.config/configstore 
/root/.local/bower
```

So with everything I have now going into /tmp there are only these 3 /paths above to clean out, not really much of anything to deal with.

Also I was hoping you were into this, because I tested only installing bower and grunt into /tmp and then having them both make their symlinks to /usr/bin and when I did this Popcorn-Time built ok, so I wanted to also test it for the node, but I'm not one experienced enough to know if Popcorn-Time will still want some other parts of it installed into the system to work properly. I guess the only way will be to play and try.

Well I guess you're not into this cause you closed it, kind of made me sad, again, was hoping you were into this.

But thanks again for your time, I do appreciate it! :)

**Comment by fsLeg** [comment]
> I hope I didn't say something to upset you that you closed this?

I explained why I closed the issue: I don't see the point. If the static build provided by the developers stops working, then I'll look into compiling from source, and even then I'll choose the stable releases.

> With the `./node_modules` not sure I follow

The dot here represents the current working directory, i. e. if I have Popcorn-Time's source tree in `/home/fsleg/tgz/popcorntime-git`, when I `cd` in it and issue `npm install` commands, bower, grunt and all other modules get in `/home/fsleg/tgz/popcorntime-git/node_modules`.

I am not into building the latest git version, because everything works just fine the way it is. As I said earlier, I'll look into compiling from source closer if the pre-compiled static builds stop working. Thank you for sharing your findings, by the way, I learned something.

**Comment by ghost** [comment]
Hi,

Well glad you were not upset, wheeew... :)

Oh by the way I forgot to mention, mpv crashes in popcorn-time, it won't even play for a minute then it just stops, the log out shows the quit cmd was sent to it. So I posted a bug report, and then I posted a report to popcorn and a popcorn developer said there was a fix for it. So not sure where the bug came from, mpv or popcorn.

For now in the ~/.mpv/config I'm using; `terminal=no` someone posted this at mpv and it seems to be doing the trick for now.

Also in vlc and mpv the audo play back isn't consistent, I read something about possible lack of codec support, so  not sure, sometimes you play a video and the audio plays ok, then you stop the video and start it over and no sound.

Do you now mpv? http://mpv.io/ This thing smokes mplayer and vlc, it also has a new OpenGL work over in it, and the resources it uses is the lowest of all the players!

So with these 2 issues, that is why I was looking at the git for the latest version, sheesh surprised I forgot to menton this, hehe... :)

Reports;
https://github.com/mpv-player/mpv/issues/1710
